[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "parsers"
version = "0.0.1"
dependencies = [
    "PyMuPDF==1.24.10",
    "pymupdf4llm==0.0.13",
]

[tool.setuptools.packages]
find = {}